name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build frontend
      run: npm run build

    - name: Deploy to cPanel
  env:
    CPANEL_API_TOKEN: ${{ secrets.CPANEL_API_TOKEN }}
    CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
    CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
  run: |
    # Compress the Next.js build and required files
    zip -r Energy-C-Frontend.zip .next public package.json next.config.js node_modules

    # Upload the zip file to cPanel
    curl -X POST "${CPANEL_HOST}/execute/Fileman/upload_files" \
      -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
      -F "dir=/home/${CPANEL_USERNAME}/public_html/Energy-C-Frontend" \
      -F "file=@Energy-C-Frontend.zip"

    # Extract the zip file in the frontend directory
    curl -X POST "${CPANEL_HOST}/execute/Fileman/extract" \
      -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
      -d "source=/home/${CPANEL_USERNAME}/public_html/Energy-C-Frontend/Energy-C-Frontend.zip" \
      -d "destination=/home/${CPANEL_USERNAME}/public_html/Energy-C-Frontend" \
      -d "clear_path=1"
